import Link from 'next/link'

const rows = [
  { product: 'Nike Air Max 90', source: 'SneakerWorld', own: '149,90 €', market: '132,00 €', delta: '-11,9 %', status: 'Kritisch' },
  { product: 'Adidas Samba OG', source: 'Urban Kicks', own: '119,00 €', market: '115,50 €', delta: '-2,9 %', status: 'Prüfen' },
  { product: 'New Balance 550', source: 'Solebox', own: '139,95 €', market: '144,00 €', delta: '+2,9 %', status: 'Stabil' },
  { product: 'Asics Gel-Kayano 14', source: 'Run Supply', own: '169,90 €', market: '159,99 €', delta: '-5,8 %', status: 'Kritisch' },
  { product: 'Salomon XT-6', source: 'Trail Dept.', own: '180,00 €', market: '184,95 €', delta: '+2,8 %', status: 'Stabil' },
]

function MetricBars({ color = '#635bff' }: { color?: string }) {
  return <div className="flex h-24 items-end gap-1" aria-label="Preisentwicklung">{[32,42,38,51,47,60,56,68,63,76,71,84].map((height,index)=><span key={`${height}-${index}`} className="flex-1" style={{height:`${height}%`,backgroundColor:color,opacity:.28+index*.055}} />)}</div>
}

function LinearWorkspaceConcept() {
  return <main className="min-h-[calc(100vh-3rem)] bg-[#111113] text-[#e8e8eb]"><div className="grid min-h-[calc(100vh-3rem)] lg:grid-cols-[15rem_1fr]">
    <aside className="border-b border-white/10 bg-[#171719] p-4 lg:border-b-0 lg:border-r"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-md bg-[#5e6ad2] text-xs font-bold">PV</span><span className="text-sm font-medium">Smokeify</span></div><span className="text-white/30">⌄</span></div><nav className="no-scrollbar mt-5 flex gap-1 overflow-x-auto lg:mt-8 lg:flex-col" aria-label="Hauptnavigation">{['Eingang','Meine Preise','Produkte','Mitbewerber','Reports'].map((item,index)=><a key={item} href={`#${item.toLowerCase()}`} className={`shrink-0 rounded-md px-3 py-2 text-sm ${index===1?'bg-white/10 text-white':'text-white/45 hover:bg-white/5'}`}><span className="mr-3 text-white/25">{['◇','◉','□','△','≡'][index]}</span>{item}</a>)}</nav><div className="mt-7 hidden border-t border-white/10 pt-5 lg:block"><p className="px-3 text-[10px] uppercase tracking-[0.14em] text-white/25">Ansichten</p><p className="mt-3 px-3 text-sm text-white/45">⌄ Preisposition</p><p className="mt-3 px-6 text-sm text-white/65">● Handlungsbedarf</p><p className="mt-3 px-6 text-sm text-white/45">○ Alle Produkte</p></div></aside>
    <section className="min-w-0"><header className="flex min-h-14 items-center justify-between border-b border-white/10 px-5 lg:px-7"><p className="text-xs text-white/35">Preisposition / <span className="text-white/70">Meine Preise</span></p><div className="flex gap-2"><button type="button" className="hidden min-h-8 rounded-md border border-white/10 px-3 text-xs text-white/40 sm:block">⌘ K</button><Link href="/dashboard/settings" className="grid h-8 w-8 place-items-center rounded-md border border-white/10" aria-label="Einstellungen">⚙</Link></div></header><div className="mx-auto max-w-[1200px] px-5 py-8 lg:px-7"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs text-[#8b8d98]">Marktmonitor</p><h1 className="mt-2 text-2xl font-semibold">Meine Preise</h1><p className="mt-2 text-sm text-white/35">Priorisiert nach aktuellem Handlungsbedarf.</p></div><button type="button" className="min-h-9 rounded-md bg-[#5e6ad2] px-4 text-sm font-medium">Preisquelle hinzufügen</button></header>
      <section className="mt-7 overflow-hidden rounded-md border border-white/10 bg-[#171719]"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div className="flex gap-4 text-xs"><span className="font-medium text-white">Aktiv 5</span><span className="text-white/35">Beobachtet 24</span></div><button type="button" className="text-xs text-white/40">Ansicht · Filter</button></div><div className="border-b border-white/10 bg-[#141416] px-4 py-2 text-[10px] font-medium uppercase tracking-[0.1em] text-white/30">Dringend · 2</div>{rows.filter(row=>row.status==='Kritisch').map((row,index)=><div key={row.product} className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b border-white/10 px-4 py-3"><span className="text-[#f05b5b]">◆</span><div><p className="text-sm font-medium">{row.product}</p><p className="mt-1 text-xs text-white/30">PV-{102+index} · {row.source}</p></div><div className="text-right"><p className="text-sm text-[#ff7b72]">{row.delta}</p><p className="mt-1 text-[10px] text-white/25">{row.market}</p></div></div>)}<div className="border-b border-white/10 bg-[#141416] px-4 py-2 text-[10px] font-medium uppercase tracking-[0.1em] text-white/30">Weitere Produkte · 3</div>{rows.filter(row=>row.status!=='Kritisch').map((row)=><div key={row.product} className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b border-white/10 px-4 py-3 last:border-b-0"><span className={row.status==='Stabil'?'text-[#45b882]':'text-[#e0a82e]'}>●</span><div><p className="text-sm font-medium">{row.product}</p><p className="mt-1 text-xs text-white/30">{row.source}</p></div><span className={row.delta.startsWith('+')?'text-sm text-[#45b882]':'text-sm text-[#e0a82e]'}>{row.delta}</span></div>)}</section>
    </div></section>
  </div></main>
}

function StripeAnalyticsConcept() {
  return <main className="min-h-[calc(100vh-3rem)] bg-[#f6f8fa] text-[#30313d]"><div className="grid min-h-[calc(100vh-3rem)] lg:grid-cols-[13rem_1fr]">
    <aside className="hidden border-r border-[#d8dee4] bg-[#f7f9fb] p-4 lg:block"><div className="flex items-center gap-3 px-2"><span className="grid h-8 w-8 place-items-center rounded bg-[#635bff] text-xs font-black text-white">PV</span><span className="text-sm font-semibold">Smokeify</span></div><nav className="mt-8 space-y-1" aria-label="Hauptnavigation">{['Start','Preise','Produkte','Mitbewerber','Berichte'].map((item,index)=><a key={item} href={`#${item.toLowerCase()}`} className={`block rounded-md px-3 py-2 text-sm ${index===0?'bg-[#e9e8ff] font-medium text-[#4f46d8]':'text-[#697386] hover:bg-white'}`}>{item}</a>)}</nav><div className="mt-8 border-t border-[#d8dee4] pt-5"><p className="px-3 text-[10px] font-semibold uppercase text-[#87909c]">Produkte</p><p className="mt-3 px-3 text-sm text-[#697386]">Radar</p><p className="mt-3 px-3 text-sm text-[#697386]">Benachrichtigungen</p></div></aside>
    <section className="min-w-0"><header className="flex min-h-14 items-center justify-between border-b border-[#d8dee4] bg-white px-5 lg:px-7"><button type="button" className="text-sm text-[#697386]">⌕ Suchen …</button><div className="flex gap-3"><span className="text-xs text-[#697386]">Testmodus</span><Link href="/dashboard/settings" className="text-xs font-medium">Einstellungen</Link></div></header><div className="mx-auto max-w-[1200px] px-5 py-8 lg:px-7"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-semibold tracking-[-0.02em]">Marktübersicht</h1><p className="mt-2 text-sm text-[#697386]">Aktuelle Performance deines Sortiments.</p></div><button type="button" className="min-h-9 rounded-md bg-[#635bff] px-4 text-sm font-medium text-white shadow-sm">Preise abrufen</button></header>
      <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Kennzahlen">{[['24','Überwachte Preise'],['2','Handlungsbedarf'],['+3,8 %','Marktvorteil'],['98,6 %','Erfolgsquote']].map(([value,label],index)=><article key={label} className="rounded-md border border-[#d8dee4] bg-white p-5 shadow-[0_1px_2px_rgba(48,49,61,.04)]"><div className="flex items-center justify-between"><p className="text-xs text-[#697386]">{label}</p><span className={`h-2 w-2 rounded-full ${index===1?'bg-[#df5b5b]':'bg-[#38a169]'}`} /></div><p className="mt-5 text-2xl font-semibold">{value}</p></article>)}</section>
      <section className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><article className="rounded-md border border-[#d8dee4] bg-white p-5"><div className="flex justify-between"><div><h2 className="text-sm font-semibold">Preisposition</h2><p className="mt-1 text-xs text-[#87909c]">Letzte 14 Tage</p></div><span className="text-xs text-[#697386]">Täglich⌄</span></div><div className="mt-7"><MetricBars /></div></article><article className="rounded-md border border-[#d8dee4] bg-white p-5"><h2 className="text-sm font-semibold">Offene Hinweise</h2><div className="mt-5 space-y-5">{[['Air Max 90','11,9 % unterboten'],['Gel-Kayano 14','5,8 % unterboten'],['Run Supply','Quelle verlangsamt']].map(([title,detail],index)=><div key={title} className="flex gap-3"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${index<2?'bg-[#df5b5b]':'bg-[#e4a72e]'}`} /><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-[#87909c]">{detail}</p></div></div>)}</div></article></section>
      <section className="mt-5 overflow-hidden rounded-md border border-[#d8dee4] bg-white"><div className="border-b border-[#e6eaed] p-4"><h2 className="text-sm font-semibold">Neueste Preise</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-xs text-[#697386]"><tr><th className="p-4 font-medium">Produkt</th><th className="p-4 font-medium">Eigener Preis</th><th className="p-4 font-medium">Markt</th><th className="p-4 font-medium">Abweichung</th></tr></thead><tbody>{rows.slice(0,4).map(row=><tr key={row.product} className="border-t border-[#edf0f2]"><td className="p-4 font-medium">{row.product}</td><td className="p-4">{row.own}</td><td className="p-4">{row.market}</td><td className={row.delta.startsWith('-')?'p-4 text-[#c94444]':'p-4 text-[#16845b]'}>{row.delta}</td></tr>)}</tbody></table></div></section>
    </div></section>
  </div></main>
}

function MerchantAdminConcept() {
  return <main className="min-h-[calc(100vh-3rem)] bg-[#f1f1f1] text-[#303030]"><div className="grid min-h-[calc(100vh-3rem)] lg:grid-cols-[15rem_1fr]">
    <aside className="border-b border-[#d4d4d4] bg-[#ebebeb] p-4 lg:border-b-0 lg:border-r"><div className="flex items-center justify-between"><p className="text-sm font-semibold">Smokeify Store</p><span>•••</span></div><nav className="no-scrollbar mt-4 flex gap-1 overflow-x-auto lg:flex-col" aria-label="Hauptnavigation">{['Home','Bestellungen','Produkte','Kunden','Analysen'].map((item,index)=><a key={item} href={`#${item.toLowerCase()}`} className={`shrink-0 rounded-lg px-3 py-2 text-sm ${index===2?'bg-white font-semibold shadow-sm':'text-[#5c5c5c] hover:bg-white/60'}`}>{item}</a>)}</nav><div className="mt-6 hidden lg:block"><p className="px-3 text-xs text-[#707070]">Vertriebskanäle</p><p className="mt-3 px-3 text-sm">◉ PriceVault</p><p className="mt-3 px-3 text-sm text-[#707070]">⊕ Apps hinzufügen</p></div></aside>
    <section className="min-w-0"><header className="flex min-h-14 items-center justify-between border-b border-[#d4d4d4] bg-white px-5"><button type="button" className="min-h-8 w-full max-w-md rounded-lg bg-[#ededed] px-3 text-left text-sm text-[#6b6b6b]">⌕ Suchen</button><Link href="/dashboard/settings" className="ml-4 grid h-8 w-8 place-items-center rounded-full bg-[#303030] text-xs text-white">JS</Link></header><div className="mx-auto max-w-[1050px] px-5 py-7"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-xl font-bold">Preisüberwachung</h1><p className="mt-1 text-sm text-[#6d6d6d]">24 Produkte in deinem Sortiment.</p></div><div className="flex gap-2"><button type="button" className="min-h-9 rounded-lg border border-[#b9b9b9] bg-white px-3 text-sm font-medium">Exportieren</button><button type="button" className="min-h-9 rounded-lg bg-[#303030] px-3 text-sm font-medium text-white">Quelle hinzufügen</button></div></header>
      <section className="mt-6 rounded-lg border border-[#d4d4d4] bg-white"><div className="grid sm:grid-cols-3">{[['2','Produkte prüfen'],['9','Preisführer'],['98,6 %','Quellen aktiv']].map(([value,label],index)=><article key={label} className={`p-5 ${index<2?'border-b border-[#e2e2e2] sm:border-b-0 sm:border-r':''}`}><p className="text-2xl font-bold">{value}</p><p className="mt-2 text-sm text-[#6d6d6d]">{label}</p></article>)}</div></section>
      <section className="mt-5 overflow-hidden rounded-lg border border-[#d4d4d4] bg-white"><div className="flex flex-col justify-between gap-3 border-b border-[#dedede] p-4 sm:flex-row sm:items-center"><div className="flex gap-4 text-sm"><span className="border-b-2 border-[#303030] pb-2 font-semibold">Alle</span><span className="text-[#707070]">Kritisch</span><span className="text-[#707070]">Stabil</span></div><button type="button" className="min-h-8 rounded-lg border border-[#c9c9c9] px-3 text-xs">Sortieren und filtern</button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#fafafa] text-xs text-[#6d6d6d]"><tr><th className="p-4 font-medium">Produkt</th><th className="p-4 font-medium">Eigener Preis</th><th className="p-4 font-medium">Niedrigster Preis</th><th className="p-4 font-medium">Status</th></tr></thead><tbody>{rows.map(row=><tr key={row.product} className="border-t border-[#ededed] hover:bg-[#fafafa]"><td className="p-4"><p className="font-medium">{row.product}</p><p className="mt-1 text-xs text-[#7b7b7b]">{row.source}</p></td><td className="p-4">{row.own}</td><td className="p-4">{row.market}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs ${row.status==='Stabil'?'bg-[#dff3e8] text-[#176b45]':row.status==='Kritisch'?'bg-[#fde4e1] text-[#a83932]':'bg-[#fff0c7] text-[#7d5d08]'}`}>{row.status}</span></td></tr>)}</tbody></table></div></section>
    </div></section>
  </div></main>
}

function NotionDatabaseConcept() {
  return <main className="min-h-[calc(100vh-3rem)] bg-white text-[#37352f]"><div className="grid min-h-[calc(100vh-3rem)] lg:grid-cols-[15rem_1fr]">
    <aside className="hidden bg-[#f7f7f5] p-3 lg:block"><div className="flex items-center justify-between rounded-md px-2 py-2"><p className="text-sm font-semibold">Smokeify Workspace</p><span className="text-[#9b9a97]">⌄</span></div><nav className="mt-3 space-y-1" aria-label="Hauptnavigation">{['⌕ Suche','⌂ Home','◫ Preisübersicht','□ Produkte','☆ Mitbewerber'].map((item,index)=><a key={item} href="#" className={`block rounded-md px-3 py-2 text-sm ${index===2?'bg-[#e8e8e5] font-medium':'text-[#6f6e69] hover:bg-[#ededeb]'}`}>{item}</a>)}</nav><div className="mt-7"><p className="px-3 text-xs text-[#9b9a97]">Teamspaces</p><p className="mt-3 px-3 text-sm">⌄ Marktmonitor</p><p className="mt-3 px-6 text-sm text-[#6f6e69]">• Alarme</p><p className="mt-3 px-6 text-sm text-[#6f6e69]">• Reports</p></div></aside>
    <section className="min-w-0"><header className="flex min-h-12 items-center justify-between border-b border-[#ededeb] px-4"><p className="text-sm">Marktmonitor / Preisübersicht</p><div className="flex gap-4 text-sm"><span>Teilen</span><span>☆</span><Link href="/dashboard/settings">•••</Link></div></header><div className="mx-auto max-w-[1100px] px-5 py-10 lg:px-12"><div className="text-5xl">◫</div><h1 className="mt-5 text-4xl font-bold tracking-[-0.04em]">Preisübersicht</h1><p className="mt-3 text-sm text-[#787774]">Alle überwachten Produkte, Marktpreise und Entscheidungen an einem Ort.</p>
      <section className="mt-8 flex flex-wrap items-center justify-between gap-3 border-b border-[#e6e6e4] pb-2"><div className="flex gap-1 text-sm"><button type="button" className="rounded-md bg-[#f1f1ef] px-3 py-2 font-medium">Tabelle</button><button type="button" className="rounded-md px-3 py-2 text-[#787774]">Kritisch</button><button type="button" className="rounded-md px-3 py-2 text-[#787774]">Preisführer</button><button type="button" className="rounded-md px-3 py-2 text-[#787774]">+ Ansicht</button></div><div className="flex gap-3 text-sm text-[#787774]"><span>Filter</span><span>Sortieren</span><button type="button" className="rounded-md bg-[#2383e2] px-3 py-1.5 text-white">Neu</button></div></section>
      <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="text-xs font-normal text-[#787774]"><tr><th className="border-b border-r border-[#e6e6e4] p-2 font-normal">Aa Produkt</th><th className="border-b border-r border-[#e6e6e4] p-2 font-normal">◉ Status</th><th className="border-b border-r border-[#e6e6e4] p-2 font-normal"># Eigener Preis</th><th className="border-b border-r border-[#e6e6e4] p-2 font-normal"># Marktpreis</th><th className="border-b border-[#e6e6e4] p-2 font-normal">Δ Differenz</th></tr></thead><tbody>{rows.map(row=><tr key={row.product} className="hover:bg-[#fafafa]"><td className="border-b border-r border-[#e6e6e4] p-3 font-medium underline decoration-[#d3d3d1]">{row.product}</td><td className="border-b border-r border-[#e6e6e4] p-3"><span className={`rounded px-2 py-1 text-xs ${row.status==='Stabil'?'bg-[#dbeddb] text-[#32633b]':row.status==='Kritisch'?'bg-[#ffe2dd] text-[#9b3b35]':'bg-[#fdecc8] text-[#7c5d1c]'}`}>{row.status}</span></td><td className="border-b border-r border-[#e6e6e4] p-3">{row.own}</td><td className="border-b border-r border-[#e6e6e4] p-3">{row.market}</td><td className={`border-b border-[#e6e6e4] p-3 ${row.delta.startsWith('-')?'text-[#c64c45]':'text-[#2f7b49]'}`}>{row.delta}</td></tr>)}</tbody></table></div><button type="button" className="mt-2 px-2 py-2 text-sm text-[#9b9a97]">+ Neu</button>
    </div></section>
  </div></main>
}

function RetoolOpsConcept() {
  return <main className="min-h-[calc(100vh-3rem)] bg-[#f4f5f7] text-[#262b33]"><header className="border-b border-[#d9dde3] bg-white"><div className="flex min-h-14 items-center justify-between px-4"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded bg-[#3b62f6] text-xs font-bold text-white">PV</span><p className="text-sm font-semibold">Price Operations</p><span className="rounded bg-[#edf0f4] px-2 py-1 text-[10px] text-[#687180]">PRODUCTION</span></div><div className="flex gap-3"><button type="button" className="min-h-8 rounded border border-[#ccd2da] px-3 text-xs">Refresh</button><Link href="/dashboard/settings" className="min-h-8 rounded bg-[#3b62f6] px-3 py-2 text-xs text-white">Settings</Link></div></div></header>
    <div className="grid lg:grid-cols-[12rem_1fr_16rem]"><aside className="hidden border-r border-[#d9dde3] bg-white p-3 lg:block"><p className="px-2 text-[10px] font-semibold uppercase text-[#8a93a0]">Pages</p>{['Dashboard','Products','Competitors','Alert queue'].map((item,index)=><a key={item} href="#" className={`mt-1 block rounded px-3 py-2 text-sm ${index===0?'bg-[#edf2ff] font-medium text-[#3155cf]':'text-[#5f6875]'}`}>{item}</a>)}<p className="mt-7 px-2 text-[10px] font-semibold uppercase text-[#8a93a0]">Resources</p><p className="mt-3 px-3 text-xs text-[#5f6875]">● Supabase</p><p className="mt-3 px-3 text-xs text-[#5f6875]">● Browserless</p></aside>
      <section className="min-w-0 p-4 lg:p-5"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-xl font-semibold">Price monitoring console</h1><p className="mt-1 text-xs text-[#77818e]">Operational view · updated 12 minutes ago</p></div><button type="button" className="min-h-9 rounded bg-[#3b62f6] px-4 text-sm font-medium text-white">Run scrape job</button></header><section className="mt-5 grid gap-3 sm:grid-cols-4">{[['24','Products'],['12','Sources'],['2','Alerts'],['98.6%','Success']].map(([value,label])=><article key={label} className="rounded border border-[#d9dde3] bg-white p-4"><p className="text-2xl font-semibold">{value}</p><p className="mt-2 text-xs text-[#7b8491]">{label}</p></article>)}</section>
        <section className="mt-4 rounded border border-[#d9dde3] bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e1e4e8] p-3"><div className="flex gap-2"><input className="min-h-8 rounded border border-[#ccd2da] bg-white px-3 text-xs" placeholder="Search products" aria-label="Produkte suchen" /><button type="button" className="min-h-8 rounded border border-[#ccd2da] px-3 text-xs">Status: All</button></div><button type="button" className="min-h-8 rounded border border-[#ccd2da] px-3 text-xs">Download CSV</button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-[#f7f8fa] text-[#6f7885]"><tr><th className="p-3">Product</th><th className="p-3">Source</th><th className="p-3">Our price</th><th className="p-3">Market</th><th className="p-3">Delta</th></tr></thead><tbody>{rows.map(row=><tr key={row.product} className="border-t border-[#e5e8eb]"><td className="p-3 font-medium">{row.product}</td><td className="p-3 text-[#6f7885]">{row.source}</td><td className="p-3">{row.own}</td><td className="p-3">{row.market}</td><td className={row.delta.startsWith('-')?'p-3 text-[#c84545]':'p-3 text-[#20805a]'}>{row.delta}</td></tr>)}</tbody></table></div></section>
      </section><aside className="hidden border-l border-[#d9dde3] bg-white p-4 lg:block"><p className="text-xs font-semibold">Selected row</p><p className="mt-5 text-[10px] uppercase text-[#8a93a0]">Product</p><p className="mt-1 text-sm font-medium">Nike Air Max 90</p><p className="mt-5 text-[10px] uppercase text-[#8a93a0]">Recommended price</p><p className="mt-1 text-xl font-semibold">139,00 €</p><button type="button" className="mt-6 min-h-9 w-full rounded bg-[#3b62f6] px-3 text-xs text-white">Open details</button><div className="mt-6 border-t border-[#e1e4e8] pt-5"><p className="text-[10px] uppercase text-[#8a93a0]">Query status</p><p className="mt-3 text-xs text-[#20805a]">● get_latest_prices · 84ms</p></div></aside></div>
  </main>
}

function AttioDataConcept() {
  return <main className="min-h-[calc(100vh-3rem)] bg-white text-[#202124]"><div className="grid min-h-[calc(100vh-3rem)] lg:grid-cols-[4rem_14rem_1fr]">
    <aside className="flex items-center justify-between border-b border-[#e4e5e7] bg-[#f7f7f8] p-3 lg:flex-col lg:border-b-0 lg:border-r"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#ff5a36] text-xs font-black text-white">PV</span><div className="flex gap-2 lg:flex-col">{['⌂','◫','◎','↗'].map((icon,index)=><button key={`${icon}-${index}`} type="button" className={`grid h-9 w-9 place-items-center rounded-lg ${index===1?'bg-white shadow-sm':'text-[#85878c]'}`} aria-label={['Home','Preise','Aktivität','Reports'][index]}>{icon}</button>)}</div><span className="grid h-8 w-8 place-items-center rounded-full bg-[#202124] text-[10px] text-white">JS</span></aside>
    <aside className="hidden border-r border-[#e4e5e7] p-4 lg:block"><div className="flex justify-between"><p className="text-sm font-semibold">Smokeify</p><span>⌄</span></div><p className="mt-7 text-[10px] font-semibold uppercase tracking-[0.13em] text-[#989a9f]">Listen</p>{['Alle Produkte','Handlungsbedarf','Preisführer','Fehlende Daten'].map((item,index)=><a key={item} href="#" className={`mt-2 block rounded-lg px-3 py-2 text-sm ${index===0?'bg-[#f2f2f3] font-medium':'text-[#696b70]'}`}>{item}</a>)}<p className="mt-7 text-[10px] font-semibold uppercase tracking-[0.13em] text-[#989a9f]">Objekte</p><p className="mt-3 px-3 text-sm text-[#696b70]">Produkte</p><p className="mt-3 px-3 text-sm text-[#696b70]">Mitbewerber</p><p className="mt-3 px-3 text-sm text-[#696b70]">Quellen</p></aside>
    <section className="min-w-0"><header className="flex min-h-14 items-center justify-between border-b border-[#e4e5e7] px-5"><p className="text-sm text-[#77797e]">Produkte / Alle Produkte</p><div className="flex gap-3"><button type="button" className="text-xs text-[#77797e]">⌕</button><Link href="/dashboard/settings" className="text-xs">Einstellungen</Link></div></header><div className="px-5 py-7 lg:px-8"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs text-[#8a8c91]">LISTE</p><h1 className="mt-2 text-2xl font-semibold">Alle Produkte</h1><p className="mt-2 text-sm text-[#77797e]">24 Datensätze · zuletzt aktualisiert vor 12 Minuten</p></div><button type="button" className="min-h-9 rounded-lg bg-[#202124] px-4 text-sm font-medium text-white">+ Produkt</button></header>
      <section className="mt-6 flex flex-wrap items-center justify-between gap-3 border-y border-[#e4e5e7] py-3"><div className="flex gap-2"><button type="button" className="rounded-lg bg-[#f1f1f2] px-3 py-2 text-xs">Tabelle</button><button type="button" className="rounded-lg px-3 py-2 text-xs text-[#77797e]">Board</button></div><div className="flex gap-2 text-xs"><button type="button" className="rounded-lg border border-[#dddfe2] px-3 py-2">Filter</button><button type="button" className="rounded-lg border border-[#dddfe2] px-3 py-2">Sortieren</button><button type="button" className="rounded-lg border border-[#dddfe2] px-3 py-2">Attribute</button></div></section>
      <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="text-xs text-[#85878c]"><tr><th className="border-b border-r border-[#e4e5e7] p-3 font-medium">Produkt</th><th className="border-b border-r border-[#e4e5e7] p-3 font-medium">Status</th><th className="border-b border-r border-[#e4e5e7] p-3 font-medium">Eigener Preis</th><th className="border-b border-r border-[#e4e5e7] p-3 font-medium">Marktpreis</th><th className="border-b border-[#e4e5e7] p-3 font-medium">Quelle</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.product} className="hover:bg-[#fafafa]"><td className="border-b border-r border-[#e4e5e7] p-3"><div className="flex items-center gap-3"><span className={`grid h-8 w-8 place-items-center rounded-lg text-xs font-semibold ${['bg-[#fee6df] text-[#a33a25]','bg-[#e3edff] text-[#365b9d]','bg-[#e4f2e9] text-[#2f7048]'][index%3]}`}>{row.product.split(' ').map(part=>part[0]).slice(0,2).join('')}</span><span className="font-medium">{row.product}</span></div></td><td className="border-b border-r border-[#e4e5e7] p-3"><span className={`inline-flex items-center gap-2 rounded-full px-2 py-1 text-xs ${row.status==='Stabil'?'bg-[#e5f2e9] text-[#277047]':row.status==='Kritisch'?'bg-[#fde7e3] text-[#a83d31]':'bg-[#fff1cf] text-[#806011]'}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{row.status}</span></td><td className="border-b border-r border-[#e4e5e7] p-3">{row.own}</td><td className="border-b border-r border-[#e4e5e7] p-3">{row.market}</td><td className="border-b border-[#e4e5e7] p-3 text-[#77797e]">{row.source}</td></tr>)}</tbody></table></div>
    </div></section>
  </div></main>
}

function VercelCommerceConcept() {
  return <main className="min-h-[calc(100vh-3rem)] bg-white text-black">
    <header className="border-b border-[#eaeaea]"><div className="mx-auto flex min-h-16 max-w-[1400px] items-center justify-between px-5 lg:px-8"><div className="flex items-center gap-3"><span className="text-lg">▲</span><span className="text-sm font-semibold">PriceVault</span><span className="text-[#aaa]">/</span><button type="button" className="text-sm font-medium">Smokeify Store⌄</button></div><div className="flex items-center gap-5 text-sm text-[#666]"><button type="button" className="hidden sm:block">⌕ Suchen</button><Link href="/dashboard/settings">Einstellungen</Link><span className="grid h-8 w-8 place-items-center rounded-full bg-black text-xs text-white">JS</span></div></div><nav className="no-scrollbar mx-auto flex max-w-[1400px] overflow-x-auto px-5 lg:px-8" aria-label="Hauptnavigation">{['Übersicht','Produkte','Mitbewerber','Alarme','Reports'].map((item,index)=><a key={item} href={`#${item.toLowerCase()}`} className={`shrink-0 border-b-2 px-4 py-4 text-sm ${index===1?'border-black font-medium':'border-transparent text-[#666]'}`}>{item}</a>)}</nav></header>
    <div className="mx-auto max-w-[1180px] px-5 py-10 lg:px-8"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm text-[#666]">Sortiment</p><h1 className="mt-1 text-2xl font-semibold tracking-[-0.03em]">Preisüberwachung</h1><p className="mt-2 text-sm text-[#777]">24 Produkte · zuletzt vor 12 Minuten aktualisiert</p></div><div className="flex gap-2"><button type="button" className="min-h-10 rounded-md border border-[#dedede] bg-white px-4 text-sm font-medium shadow-sm">Exportieren</button><button type="button" className="min-h-10 rounded-md bg-black px-4 text-sm font-medium text-white">Quelle hinzufügen</button></div></header>
      <section className="mt-8 grid overflow-hidden rounded-md border border-[#e5e5e5] sm:grid-cols-3" aria-label="Kennzahlen">{[['2','Produkte prüfen','−1 seit gestern'],['9','Preisführer','37,5 % des Sortiments'],['98,6 %','Quellen aktiv','12 von 12 erreichbar']].map(([value,label,detail],index)=><article key={label} className={`p-5 ${index<2?'border-b border-[#e5e5e5] sm:border-b-0 sm:border-r':''}`}><div className="flex items-center justify-between"><p className="text-sm text-[#666]">{label}</p><span className={`h-2 w-2 rounded-full ${index===0?'bg-[#f5a623]':'bg-[#1aab40]'}`} /></div><p className="mt-5 text-3xl font-semibold tracking-[-0.04em]">{value}</p><p className="mt-2 text-xs text-[#888]">{detail}</p></article>)}</section>
      <section className="mt-6 grid gap-6 xl:grid-cols-[1fr_19rem]"><div className="overflow-hidden rounded-md border border-[#e5e5e5]"><div className="flex flex-col justify-between gap-4 border-b border-[#e5e5e5] p-4 sm:flex-row sm:items-center"><div className="flex gap-4 text-sm"><button type="button" className="font-medium">Alle</button><button type="button" className="text-[#777]">Kritisch</button><button type="button" className="text-[#777]">Stabil</button></div><div className="flex gap-2"><button type="button" className="min-h-8 rounded-md border border-[#dedede] px-3 text-xs">Filter</button><button type="button" className="min-h-8 rounded-md border border-[#dedede] px-3 text-xs">Sortieren</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#fafafa] text-xs text-[#777]"><tr><th className="p-4 font-medium">Produkt</th><th className="p-4 font-medium">Eigener Preis</th><th className="p-4 font-medium">Marktpreis</th><th className="p-4 font-medium">Status</th></tr></thead><tbody>{rows.map(row=><tr key={row.product} className="border-t border-[#ededed] hover:bg-[#fafafa]"><td className="p-4"><p className="font-medium">{row.product}</p><p className="mt-1 text-xs text-[#888]">{row.source}</p></td><td className="p-4">{row.own}</td><td className="p-4">{row.market}</td><td className="p-4"><span className="inline-flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${row.status==='Stabil'?'bg-[#1aab40]':row.status==='Kritisch'?'bg-[#e5484d]':'bg-[#f5a623]'}`} />{row.status}</span></td></tr>)}</tbody></table></div></div>
        <aside className="space-y-4"><section className="rounded-md border border-[#e5e5e5]"><div className="border-b border-[#e5e5e5] p-4"><h2 className="text-sm font-semibold">Handlungsbedarf</h2><p className="mt-1 text-xs text-[#888]">Nach Priorität</p></div><div className="divide-y divide-[#ededed]">{rows.filter(row=>row.status==='Kritisch').map((row,index)=><div key={row.product} className="p-4"><div className="flex items-center justify-between"><span className="text-xs text-[#888]">0{index+1}</span><span className="text-xs font-medium text-[#d32f2f]">{row.delta}</span></div><p className="mt-3 text-sm font-medium">{row.product}</p><button type="button" className="mt-3 text-xs font-medium">Prüfen →</button></div>)}</div></section><section className="rounded-md border border-[#d9eadf] bg-[#f3faf5] p-4"><p className="text-xs font-medium text-[#26734d]">Systemstatus</p><p className="mt-2 text-sm font-medium">Alle Quellen erreichbar</p><p className="mt-1 text-xs text-[#668273]">Nächster Lauf in 5:24 Std.</p></section></aside>
      </section>
    </div>
  </main>
}

export type CompanyConceptName = 'linear-workspace' | 'stripe-analytics' | 'merchant-admin' | 'notion-database' | 'retool-ops' | 'attio-data' | 'vercel-commerce'

export function CompanyInspiredConceptPreview({ concept }: { concept: CompanyConceptName }) {
  switch (concept) {
    case 'linear-workspace': return <LinearWorkspaceConcept />
    case 'stripe-analytics': return <StripeAnalyticsConcept />
    case 'merchant-admin': return <MerchantAdminConcept />
    case 'notion-database': return <NotionDatabaseConcept />
    case 'retool-ops': return <RetoolOpsConcept />
    case 'attio-data': return <AttioDataConcept />
    case 'vercel-commerce': return <VercelCommerceConcept />
  }
}
