import Link from 'next/link'

const prices = [
  { product: 'Nike Air Max 90', source: 'SneakerWorld', old: '145,00 €', own: '149,90 €', market: '132,00 €', delta: '-11,9 %', down: true },
  { product: 'Adidas Samba OG', source: 'Urban Kicks', old: '118,00 €', own: '119,00 €', market: '115,50 €', delta: '-2,9 %', down: true },
  { product: 'New Balance 550', source: 'Solebox', old: '142,00 €', own: '139,95 €', market: '144,00 €', delta: '+2,9 %', down: false },
  { product: 'Asics Gel-Kayano 14', source: 'Run Supply', old: '164,90 €', own: '169,90 €', market: '159,99 €', delta: '-5,8 %', down: true },
  { product: 'Salomon XT-6', source: 'Trail Dept.', old: '179,00 €', own: '180,00 €', market: '184,95 €', delta: '+2,8 %', down: false },
]

const navigation = ['Übersicht', 'Produkte', 'Quellen', 'Alarme', 'Reports']

function RadarConcept() {
  return (
    <main className="min-h-[calc(100vh-3rem)] bg-[#07100d] text-[#dcebe4] [background-image:repeating-linear-gradient(135deg,rgba(63,255,166,.018)_0,rgba(63,255,166,.018)_1px,transparent_1px,transparent_9px)]">
      <header className="border-b border-[#234035] bg-[#0a1511]"><div className="mx-auto flex min-h-16 max-w-[1550px] items-center justify-between px-5 lg:px-8"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center border border-[#55efaa] font-mono text-xs font-bold text-[#55efaa]">PV</span><div><p className="font-mono text-sm font-bold uppercase">Price Radar</p><p className="font-mono text-[9px] uppercase tracking-[0.15em] text-[#698a7d]">Sector DACH / live surveillance</p></div></div><div className="flex items-center gap-3"><span className="hidden font-mono text-[10px] text-[#55efaa] sm:block">● NETWORK ONLINE</span><Link href="/dashboard/settings" className="grid h-9 w-9 place-items-center border border-[#29483c]" aria-label="Einstellungen">⚙</Link></div></div><nav className="no-scrollbar mx-auto flex max-w-[1550px] overflow-x-auto border-t border-[#1b332a] px-5 lg:px-8" aria-label="Hauptnavigation">{navigation.map((item, index) => <a key={item} href={`#${item.toLowerCase()}`} className={`shrink-0 border-x border-[#1b332a] px-5 py-3 font-mono text-[10px] uppercase ${index === 0 ? 'bg-[#55efaa] font-bold text-[#07100d]' : 'text-[#769486] hover:bg-[#10231b]'}`}>0{index + 1} {item}</a>)}</nav></header>

      <div className="mx-auto max-w-[1550px] px-5 py-7 lg:px-8 lg:py-10">
        <header className="flex flex-col justify-between gap-5 border-b border-[#29483c] pb-7 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#55efaa]">Market scan / 14:36:08 CET</p><h1 className="mt-3 text-4xl font-bold uppercase tracking-[0.04em] sm:text-5xl">Radar overview</h1></div><button type="button" className="min-h-11 border border-[#55efaa] px-5 font-mono text-xs font-bold uppercase text-[#55efaa] hover:bg-[#55efaa] hover:text-[#07100d]">Neuen Sweep starten</button></header>

        <section className="mt-5 grid gap-5 xl:grid-cols-[25rem_1fr]">
          <article className="border border-[#29483c] bg-[#0a1511] p-5"><div className="flex items-center justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-[#698a7d]">Sources active</p><p className="mt-2 font-mono text-3xl font-bold">12 / 12</p></div><span className="font-mono text-[9px] text-[#55efaa]">SWEEP 184</span></div><div className="relative mx-auto mt-5 aspect-square max-w-[290px] overflow-hidden rounded-full border border-[#55efaa]/65 [background-image:repeating-radial-gradient(circle,transparent_0,transparent_23px,rgba(85,239,170,.16)_24px,transparent_25px),linear-gradient(90deg,transparent_49.7%,rgba(85,239,170,.18)_50%,transparent_50.3%),linear-gradient(transparent_49.7%,rgba(85,239,170,.18)_50%,transparent_50.3%)]"><span className="absolute inset-0 rounded-full [background:conic-gradient(from_0deg,transparent_0deg,rgba(85,239,170,.42)_38deg,transparent_64deg)] animate-[spin_4s_linear_infinite]" /><span className="absolute left-[63%] top-[28%] h-2 w-2 rounded-full bg-[#ff6c4c] shadow-[0_0_0_6px_rgba(255,108,76,.12),0_0_14px_#ff6c4c] animate-pulse" /><span className="absolute left-[31%] top-[61%] h-1.5 w-1.5 rounded-full bg-[#55efaa] shadow-[0_0_12px_#55efaa]" /><span className="absolute left-[72%] top-[68%] h-1.5 w-1.5 rounded-full bg-[#55efaa] shadow-[0_0_12px_#55efaa]" /><span className="absolute inset-[49%] rounded-full bg-[#55efaa]" /></div><div className="mt-5 flex justify-between font-mono text-[9px] text-[#698a7d]"><span>RANGE 100%</span><span>LATENCY 840MS</span></div></article>

          <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-3" aria-label="Kennzahlen">{[['02', 'Neue Pings'], ['+3,8 %', 'Marktvorteil'], ['98,6 %', 'Signalqualität']].map(([value, label], index) => <article key={label} className="border border-[#29483c] bg-[#0a1511] p-5"><span className={`block h-1 w-10 ${index === 0 ? 'bg-[#ff6c4c]' : 'bg-[#55efaa]'}`} /><p className="mt-5 font-mono text-3xl font-bold">{value}</p><p className="mt-2 font-mono text-[9px] uppercase text-[#698a7d]">{label}</p></article>)}</section><section className="border border-[#29483c] bg-[#0a1511]"><div className="flex justify-between border-b border-[#29483c] p-4"><div><h2 className="font-mono text-sm font-bold uppercase">Detected deviations</h2><p className="mt-1 font-mono text-[9px] text-[#698a7d]">Signalstärke nach Preisabstand</p></div><span className="font-mono text-[10px] text-[#ff856b]">2 PRIORITY</span></div><div className="divide-y divide-[#1d362c]">{prices.map((price, index) => <div key={price.product} className="grid grid-cols-[auto_1fr_auto] items-center gap-4 p-4"><span className={`relative h-3 w-3 rounded-full ${price.down ? 'bg-[#ff6c4c] shadow-[0_0_12px_#ff6c4c]' : 'bg-[#55efaa]'}`}>{price.down && index < 2 ? <span className="absolute -inset-2 rounded-full border border-[#ff6c4c]/50 animate-ping" /> : null}</span><div><p className="text-sm font-semibold">{price.product}</p><p className="mt-1 font-mono text-[9px] text-[#698a7d]">{price.source} / {price.market}</p></div><span className={`font-mono text-xs font-bold ${price.down ? 'text-[#ff856b]' : 'text-[#55efaa]'}`}>{price.delta}</span></div>)}</div></section></div>
        </section>
      </div>
    </main>
  )
}

function TerminalConcept() {
  return (
    <main className="min-h-[calc(100vh-3rem)] bg-[#050706] font-mono text-[#9bf6b4] [background-image:repeating-linear-gradient(0deg,rgba(255,255,255,.018)_0,rgba(255,255,255,.018)_1px,transparent_1px,transparent_4px)]">
      <header className="border-b border-[#275d37] bg-[#080c09]"><div className="flex min-h-12 items-center justify-between px-4 sm:px-6"><p className="text-xs">pricevault@smokeify:~/market</p><div className="flex gap-2"><span className="h-3 w-3 rounded-full bg-[#ff665c]" /><span className="h-3 w-3 rounded-full bg-[#f5c451]" /><span className="h-3 w-3 rounded-full bg-[#72dc91]" /></div></div></header>
      <div className="mx-auto max-w-[1450px] p-4 sm:p-6 lg:p-8">
        <nav className="no-scrollbar flex overflow-x-auto border-y border-[#275d37] py-2 text-xs" aria-label="Hauptnavigation">{navigation.map((item, index) => <a key={item} href={`#${item.toLowerCase()}`} className={`shrink-0 px-4 py-2 ${index === 0 ? 'bg-[#9bf6b4] text-[#050706]' : 'text-[#62a876] hover:bg-[#102116]'}`}>[{index + 1}] {item.toLowerCase()}</a>)}</nav>
        <header className="py-8"><p className="text-xs text-[#62a876]">Last login: Thu Jul 02 14:36:08 on ttys001</p><h1 className="mt-4 text-xl font-normal sm:text-3xl"><span className="text-white">$</span> pv status --workspace smokeify</h1><p className="mt-3 text-xs text-[#62a876]">Loading market snapshot... <span className="text-[#9bf6b4]">done</span></p></header>
        <section className="grid gap-5 xl:grid-cols-[1fr_22rem]">
          <div className="min-w-0"><div className="overflow-x-auto border border-[#275d37] p-4"><pre className="min-w-[720px] text-xs leading-7 text-[#9bf6b4]">{`┌──────────────────────────┬────────────┬────────────┬───────────┐\n│ PRODUCT                  │ OUR PRICE  │ MARKET LOW │ DELTA     │\n├──────────────────────────┼────────────┼────────────┼───────────┤`}</pre>{prices.map((price) => <div key={price.product} className="grid min-w-[720px] grid-cols-[1fr_12rem_12rem_10rem] border-x border-[#275d37] text-xs"><span className="border-r border-[#275d37] px-3 py-3 text-white">{price.product}</span><span className="border-r border-[#275d37] px-3 py-3">{price.own}</span><span className="border-r border-[#275d37] px-3 py-3">{price.market}</span><span className={`px-3 py-3 ${price.down ? 'text-[#ff776d]' : 'text-[#9bf6b4]'}`}>{price.delta}</span></div>)}<pre className="min-w-[720px] text-xs leading-7">└──────────────────────────┴────────────┴────────────┴───────────┘</pre></div><div className="mt-5 border border-[#275d37] p-4 text-xs leading-6"><p><span className="text-white">$</span> pv alerts --unread</p><p className="mt-2 text-[#ff776d]">! [critical] Nike Air Max 90: competitor undercut by 11.9%</p><p className="text-[#f0c95a]">! [warning] Asics Gel-Kayano 14: competitor undercut by 5.8%</p><p className="mt-2 text-[#62a876]">2 rows returned in 0.84s</p></div></div>
          <aside className="space-y-5"><div className="border border-[#275d37] p-4"><p className="text-xs text-white">SYSTEM</p><div className="mt-4 space-y-3 text-xs"><p>sources ....... 12/12</p><p>uptime ........ 98.6%</p><p>advantage ..... +3.8%</p><p>next_run ...... 05:24:18</p></div></div><button type="button" className="min-h-14 w-full border border-[#9bf6b4] bg-[#0a160e] px-4 text-left text-sm hover:bg-[#9bf6b4] hover:text-[#050706]"><span className="text-white">$</span> pv scan --now <span className="inline-block h-4 w-2 bg-[#9bf6b4] align-middle animate-[pulse_1s_steps(1)_infinite]" /></button><div className="border border-[#275d37] p-4 text-[10px] leading-5 text-[#62a876]"><p># shortcuts</p><p>g p &nbsp; products</p><p>g a &nbsp; alerts</p><p>g r &nbsp; reports</p><p>:q &nbsp;&nbsp; sign out</p></div></aside>
        </section>
      </div>
    </main>
  )
}

function DiffViewConcept() {
  return (
    <main className="min-h-[calc(100vh-3rem)] bg-[#0d1117] text-[#e6edf3]">
      <header className="border-b border-[#30363d] bg-[#010409]"><div className="mx-auto flex min-h-16 max-w-[1500px] items-center justify-between px-5 lg:px-8"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full border border-[#3d444d] font-mono text-xs">PV</span><p className="text-sm font-semibold">smokeify / price-monitor</p><span className="rounded-full border border-[#3d444d] px-2 py-1 text-[10px] text-[#8b949e]">private</span></div><Link href="/dashboard/settings" className="text-xs text-[#8b949e]">Settings</Link></div><nav className="no-scrollbar mx-auto flex max-w-[1500px] overflow-x-auto px-5 lg:px-8" aria-label="Hauptnavigation">{navigation.map((item, index) => <a key={item} href={`#${item.toLowerCase()}`} className={`shrink-0 border-b-2 px-4 py-3 text-xs ${index === 0 ? 'border-[#f78166] text-white' : 'border-transparent text-[#8b949e]'}`}>{item}</a>)}</nav></header>
      <div className="mx-auto max-w-[1250px] px-5 py-8 lg:px-8"><header className="flex flex-col justify-between gap-5 border-b border-[#30363d] pb-6 sm:flex-row sm:items-end"><div><p className="font-mono text-xs text-[#8b949e]">market-snapshot / changes</p><h1 className="mt-2 text-3xl font-semibold">Preisänderungen</h1><p className="mt-2 text-sm text-[#8b949e]"><span className="text-[#3fb950]">+2 günstiger</span> <span className="mx-2">·</span> <span className="text-[#f85149]">−3 teurer</span> seit dem letzten Lauf</p></div><button type="button" className="min-h-10 rounded-md bg-[#238636] px-4 text-sm font-semibold">Änderungen prüfen</button></header>
        <section className="mt-6 overflow-hidden rounded-md border border-[#30363d]"><div className="flex items-center justify-between border-b border-[#30363d] bg-[#161b22] px-4 py-3"><div><h2 className="text-sm font-semibold">competitor-prices.json</h2><p className="mt-1 font-mono text-[10px] text-[#8b949e]">5 Produkte · aktualisiert vor 12 Minuten</p></div><span className="font-mono text-xs text-[#8b949e]">@@ −5 +5 @@</span></div><div className="overflow-x-auto font-mono text-xs">{prices.map((price, index) => <div key={price.product} className="min-w-[760px] border-b border-[#21262d] last:border-b-0"><div className="grid grid-cols-[3rem_3rem_1.4rem_1fr_9rem] bg-[#321c20] text-[#ffa198]"><span className="border-r border-[#30363d] px-2 py-2 text-right text-[#6e7681]">{index * 2 + 41}</span><span className="border-r border-[#30363d] px-2 py-2 text-right text-[#6e7681]" /><span className="px-2 py-2">−</span><span className="px-2 py-2"><span className="text-[#8b949e]">{price.product}</span> <s className="decoration-[#f85149]">{price.old}</s></span><span className="px-2 py-2 text-right">previous</span></div><div className="grid grid-cols-[3rem_3rem_1.4rem_1fr_9rem] bg-[#12261e] text-[#7ee787]"><span className="border-r border-[#30363d] px-2 py-2 text-right text-[#6e7681]" /><span className="border-r border-[#30363d] px-2 py-2 text-right text-[#6e7681]">{index * 2 + 42}</span><span className="px-2 py-2">+</span><span className="px-2 py-2"><span className="text-[#c9d1d9]">{price.product}</span> <mark className="bg-[#2ea043]/35 px-1 text-[#aff5b4]">{price.market}</mark> <span className="ml-2 text-[#8b949e]">via {price.source}</span></span><span className={`px-2 py-2 text-right ${price.down ? 'text-[#ffa198]' : 'text-[#7ee787]'}`}>{price.delta}</span></div></div>)}</div></section>
        <section className="mt-6 grid gap-4 sm:grid-cols-3">{[['5', 'geänderte Zeilen'], ['2', 'Review-Kommentare'], ['98,6 %', 'Quellenabdeckung']].map(([value, label]) => <article key={label} className="rounded-md border border-[#30363d] bg-[#161b22] p-5"><p className="text-2xl font-semibold">{value}</p><p className="mt-2 text-xs text-[#8b949e]">{label}</p></article>)}</section>
      </div>
    </main>
  )
}

function TradingDeskConcept() {
  const ticker = [...prices, ...prices]
  return (
    <main className="min-h-[calc(100vh-3rem)] bg-[#101317] font-mono text-[#e9edf1]">
      <header className="border-b border-[#38404a] bg-[#171b20]"><div className="flex min-h-14 items-center justify-between px-4 lg:px-6"><div><span className="text-sm font-bold text-[#ffb020]">PVX</span><span className="ml-3 text-xs text-[#8b949e]">SMOKEIFY MARKET DESK</span></div><div className="flex gap-5 text-[10px]"><span className="text-[#52d49a]">DAX +0.42%</span><span className="hidden text-[#ff7b72] sm:block">EUR/USD −0.18%</span><Link href="/dashboard/settings" className="text-[#b7c2cc]">SETTINGS</Link></div></div><div className="overflow-hidden border-t border-[#38404a] bg-[#0b0e11] py-2"><div className="design-ticker-track flex w-max gap-10 whitespace-nowrap text-[10px]">{ticker.map((price, index) => <span key={`${price.product}-${index}`}><strong className="text-white">{price.product.toUpperCase()}</strong> <span>{price.market}</span> <span className={price.down ? 'text-[#ff7b72]' : 'text-[#52d49a]'}>{price.delta}</span></span>)}</div></div><nav className="no-scrollbar flex overflow-x-auto px-4 lg:px-6" aria-label="Hauptnavigation">{navigation.map((item, index) => <a key={item} href={`#${item.toLowerCase()}`} className={`shrink-0 border-b-2 px-4 py-3 text-[10px] ${index === 0 ? 'border-[#ffb020] text-white' : 'border-transparent text-[#77828d]'}`}>{item.toUpperCase()}</a>)}</nav></header>
      <div className="p-3 lg:p-5"><header className="flex flex-col justify-between gap-3 border border-[#38404a] bg-[#171b20] p-4 sm:flex-row sm:items-center"><div><p className="text-[9px] text-[#77828d]">WORKSPACE / LIVE BOOK</p><h1 className="mt-1 text-xl font-bold">MARKTÜBERSICHT</h1></div><div className="flex gap-6 text-xs"><p><span className="text-[#77828d]">SOURCES</span> 12/12</p><p><span className="text-[#77828d]">LATENCY</span> 840ms</p><p><span className="text-[#77828d]">CLOCK</span> 14:36:08</p></div></header>
        <section className="mt-3 grid gap-3 xl:grid-cols-[1.45fr_.55fr]"><div className="border border-[#38404a] bg-[#171b20]"><div className="flex justify-between border-b border-[#38404a] p-3"><h2 className="text-xs font-bold">PRICE BOOK</h2><span className="text-[9px] text-[#77828d]">AUTO-REFRESH 60S</span></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-[11px]"><thead className="bg-[#20252b] text-[#8f9aa5]"><tr><th className="p-3">INSTRUMENT</th><th className="p-3">OUR</th><th className="p-3">BID</th><th className="p-3">SPREAD</th><th className="p-3">SOURCE</th><th className="p-3">ACTION</th></tr></thead><tbody>{prices.map((price) => <tr key={price.product} className="border-t border-[#30363d] hover:bg-[#20252b]"><td className="p-3 font-bold text-white">{price.product.toUpperCase()}</td><td className="p-3">{price.own}</td><td className="p-3">{price.market}</td><td className={`p-3 font-bold ${price.down ? 'bg-[#4a2325] text-[#ff8d85]' : 'bg-[#17392d] text-[#67dba8]'}`}>{price.delta}</td><td className="p-3 text-[#8f9aa5]">{price.source}</td><td className="p-3 text-[#ffb020]">OPEN →</td></tr>)}</tbody></table></div></div><aside className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1"><div className="border border-[#38404a] bg-[#171b20] p-4"><p className="text-[9px] text-[#77828d]">MARKET POSITION</p><p className="mt-3 text-3xl font-bold text-[#52d49a]">+3.8%</p><div className="mt-4 flex h-20 items-end gap-1">{[28,40,35,51,46,60,55,68,63,75,71,84].map((height,index)=><span key={`${height}-${index}`} className="flex-1 bg-[#52d49a]" style={{height:`${height}%`,opacity:.35+index*.05}} />)}</div></div><div className="border border-[#38404a] bg-[#171b20] p-4"><div className="flex justify-between"><p className="text-[9px] text-[#77828d]">ALERT WIRE</p><span className="text-[9px] text-[#ff7b72]">02 NEW</span></div><div className="mt-4 space-y-4 text-[10px]"><p><span className="text-[#ff7b72]">14:34:02</span> AIR MAX breach −11.9%</p><p><span className="text-[#ffb020]">14:31:48</span> KAYANO spread widening</p><p><span className="text-[#52d49a]">14:28:11</span> XT-6 position improved</p></div></div></aside></section>
        <section className="mt-3 grid gap-3 sm:grid-cols-4">{[['24','INSTRUMENTS'],['02','BREACHES'],['9','LEADERS'],['98.6%','UPTIME']].map(([value,label])=><article key={label} className="border border-[#38404a] bg-[#171b20] p-4"><p className="text-2xl font-bold">{value}</p><p className="mt-2 text-[9px] text-[#77828d]">{label}</p></article>)}</section>
      </div>
    </main>
  )
}

function FieldNotebookConcept() {
  return (
    <main className="min-h-[calc(100vh-3rem)] bg-[#f8f5e9] text-[#24342e] [background-image:radial-gradient(rgba(36,52,46,.18)_1px,transparent_1px)] [background-size:20px_20px]">
      <header className="border-b-2 border-[#24342e] bg-[#f8f5e9]/95"><div className="mx-auto flex min-h-16 max-w-[1400px] items-center justify-between px-5 lg:px-8"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center border-2 border-[#24342e] text-xs font-black">PV</span><div><p className="font-serif text-lg font-bold">Field Notes</p><p className="text-[9px] uppercase tracking-[0.15em] text-[#6d7a74]">Smokeify market watch</p></div></div><Link href="/dashboard/settings" className="text-xs font-bold">Konto ↗</Link></div><nav className="no-scrollbar mx-auto flex max-w-[1400px] overflow-x-auto border-t border-[#24342e]/30 px-5 lg:px-8" aria-label="Hauptnavigation">{navigation.map((item,index)=><a key={item} href={`#${item.toLowerCase()}`} className={`shrink-0 px-4 py-3 text-xs font-semibold ${index===0?'border-b-4 border-[#d45b3e]':'text-[#65726d]'}`}>{item}</a>)}</nav></header>
      <div className="mx-auto max-w-[1350px] px-5 py-8 lg:px-8"><header className="grid gap-6 border-b-2 border-[#24342e] pb-7 lg:grid-cols-[1fr_21rem] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#d45b3e]">Eintrag 184 / 2. Juli</p><h1 className="mt-3 font-serif text-4xl font-bold sm:text-5xl">Marktbeobachtung</h1><p className="mt-3 text-sm text-[#64716c]">Ein schneller Blick auf Bewegungen, Quellen und offene Entscheidungen.</p></div><aside className="rotate-[-1deg] border border-[#d9c878] bg-[#fff3a8] p-5 shadow-[3px_4px_0_rgba(36,52,46,.18)]"><p className="[font-family:'Segoe_Print','Bradley_Hand',cursive] text-lg leading-7 text-[#574d26]">Air Max zuerst prüfen — Abstand seit Montag deutlich größer.</p><p className="mt-3 text-right text-xs italic text-[#7c6e39]">Notiz, 14:36</p></aside></header>
        <section className="grid border-b-2 border-[#24342e] sm:grid-cols-4" aria-label="Kennzahlen">{[['24','Preise'],['02','Auffällig'],['+3,8 %','Vorteil'],['12/12','Quellen']].map(([value,label],index)=><article key={label} className={`p-5 ${index<3?'sm:border-r sm:border-[#24342e]/35':''}`}><p className="font-serif text-3xl font-bold">{value}</p><p className="mt-2 text-[10px] uppercase tracking-[0.13em] text-[#67736e]">{label}</p></article>)}</section>
        <section className="mt-7 grid gap-7 xl:grid-cols-[1fr_19rem]"><div><div className="flex justify-between border-b border-[#24342e] pb-3"><h2 className="font-serif text-2xl font-bold">Beobachtete Produkte</h2><span className="text-[10px] uppercase">Nach Dringlichkeit</span></div><div className="divide-y divide-[#24342e]/30">{prices.map((price,index)=><article key={price.product} className="grid gap-3 py-5 sm:grid-cols-[2rem_1fr_auto] sm:items-center"><span className="[font-family:'Segoe_Print','Bradley_Hand',cursive] text-xl text-[#d45b3e]">{index+1}.</span><div><h3 className="font-serif text-lg font-bold">{price.product}</h3><p className="mt-1 text-xs text-[#6d7974]">{price.source} · Marktpreis {price.market}</p></div><span className={`font-mono text-sm font-bold ${price.down?'text-[#c84e34]':'text-[#28745a]'}`}>{price.delta}</span></article>)}</div></div><aside className="space-y-5"><div className="border-2 border-[#24342e] bg-[#f8f5e9] p-5"><p className="text-[10px] font-bold uppercase tracking-[0.14em]">Quellen-Checkliste</p>{['SneakerWorld','Urban Kicks','Solebox','Run Supply'].map((source,index)=><p key={source} className="mt-4 flex items-center gap-3 text-sm"><span className={`grid h-5 w-5 place-items-center border border-[#24342e] ${index<3?'bg-[#b8dfcb]':''}`}>{index<3?'✓':''}</span>{source}</p>)}</div><button type="button" className="min-h-11 w-full border-2 border-[#24342e] bg-[#d45b3e] px-4 text-sm font-bold text-white shadow-[3px_3px_0_#24342e]">Neuen Eintrag anlegen</button></aside></section>
      </div>
    </main>
  )
}

function CleanWorkspaceConcept() {
  return (
    <main className="min-h-[calc(100vh-3rem)] bg-white text-[#17211d]">
      <header className="border-b border-[#e3e8e5]"><div className="mx-auto flex min-h-16 max-w-[1400px] items-center justify-between px-5 lg:px-8"><div className="flex items-center gap-8"><Link href="/design-lab/clean-workspace" className="text-sm font-bold">PriceVault</Link><nav className="hidden gap-6 text-sm text-[#68736e] md:flex" aria-label="Hauptnavigation">{navigation.map((item,index)=><a key={item} href={`#${item.toLowerCase()}`} className={index===0?'font-semibold text-[#17211d]':''}>{item}</a>)}</nav></div><div className="flex items-center gap-3"><button type="button" className="hidden min-h-9 rounded-md border border-[#dce3df] px-3 text-xs text-[#68736e] sm:block">Suchen</button><Link href="/dashboard/settings" className="grid h-9 w-9 place-items-center rounded-full bg-[#edf2ef] text-xs font-bold" aria-label="Konto">JS</Link></div></div></header>
      <div className="mx-auto max-w-[1180px] px-5 py-10 lg:px-8 lg:py-14"><header className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-sm text-[#6b7771]">Smokeify Store</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.03em]">Preisübersicht</h1><p className="mt-2 text-sm text-[#7b8681]">Stand 2. Juli, 14:36 Uhr</p></div><button type="button" className="min-h-10 rounded-md bg-[#176b4d] px-4 text-sm font-semibold text-white">Preise aktualisieren</button></header>
        <section className="mt-10 grid gap-8 border-y border-[#e3e8e5] py-7 sm:grid-cols-4" aria-label="Kennzahlen">{[['24','Produkte'],['2','Handlungsbedarf'],['+3,8 %','Preisvorteil'],['98,6 %','Erfolgsquote']].map(([value,label],index)=><article key={label} className={index<3?'sm:border-r sm:border-[#e3e8e5]':''}><p className="text-2xl font-semibold">{value}</p><p className="mt-2 text-xs text-[#7b8681]">{label}</p></article>)}</section>
        <section className="mt-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-lg font-semibold">Produkte</h2><p className="mt-1 text-sm text-[#7b8681]">Nach größter Abweichung sortiert</p></div><div className="flex gap-2"><button type="button" className="min-h-9 rounded-md border border-[#dce3df] px-3 text-xs">Filter</button><button type="button" className="min-h-9 rounded-md border border-[#dce3df] px-3 text-xs">Export</button></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-[#dce3df] text-xs text-[#78837e]"><tr><th className="py-3 font-medium">Produkt</th><th className="py-3 font-medium">Eigener Preis</th><th className="py-3 font-medium">Marktpreis</th><th className="py-3 font-medium">Abweichung</th><th className="py-3 font-medium">Quelle</th></tr></thead><tbody>{prices.map((price)=><tr key={price.product} className="border-b border-[#edf0ee] hover:bg-[#f8faf9]"><td className="py-5 font-medium">{price.product}</td><td className="py-5">{price.own}</td><td className="py-5">{price.market}</td><td className={`py-5 font-medium ${price.down?'text-[#c9433d]':'text-[#176b4d]'}`}>{price.delta}</td><td className="py-5 text-[#7b8681]">{price.source}</td></tr>)}</tbody></table></div></section>
        <section className="mt-10 grid gap-8 border-t border-[#e3e8e5] pt-8 md:grid-cols-2"><div><p className="text-xs font-medium text-[#7b8681]">Empfehlung</p><h2 className="mt-2 text-xl font-semibold">Air Max 90 analysieren</h2><p className="mt-2 max-w-md text-sm leading-6 text-[#6f7a75]">Der größte Preisabstand im Sortiment liegt aktuell bei 11,9 %.</p></div><div className="flex items-end gap-1 text-[#176b4d]">{[33,42,39,50,46,58,54,65,61,73,68,79].map((height,index)=><span key={`${height}-${index}`} className="flex-1 bg-current" style={{height:`${height}px`,opacity:.25+index*.05}} />)}</div></section>
      </div>
    </main>
  )
}

export type SpecializedConceptName = 'radar' | 'terminal' | 'diff-view' | 'trading-desk' | 'field-notebook' | 'clean-workspace'

export function SpecializedConceptPreview({ concept }: { concept: SpecializedConceptName }) {
  switch (concept) {
    case 'radar': return <RadarConcept />
    case 'terminal': return <TerminalConcept />
    case 'diff-view': return <DiffViewConcept />
    case 'trading-desk': return <TradingDeskConcept />
    case 'field-notebook': return <FieldNotebookConcept />
    case 'clean-workspace': return <CleanWorkspaceConcept />
  }
}
